This is makeindex, version 2.16 [MiKTeX 24.1].
Scanning style file ./template.ist...........................done (27 attributes redefined, 0 ignored).
Scanning input file template.acn....done (270 entries accepted, 0 rejected).
Sorting entries.....done (2344 comparisons).
Generating output file template.acr....done (204 lines written, 0 warnings).
Output written in template.acr.
Transcript written in template.alg.
